artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/5ab8e50d1bf54f85b80504fca8d07161/artifacts
end_time: 1763306476531
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 5ab8e50d1bf54f85b80504fca8d07161
run_name: indecisive-elk-264
source_name: ''
source_type: 4
source_version: ''
start_time: 1763306465307
status: 3
tags: []
user_id: DELL
