artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/9e8cb6cd3b09432a85bf233d5ec36490/artifacts
end_time: 1763307167728
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 9e8cb6cd3b09432a85bf233d5ec36490
run_name: enthused-grub-707
source_name: ''
source_type: 4
source_version: ''
start_time: 1763307155823
status: 3
tags: []
user_id: DELL
