artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/46d63f60276145fd9ac726abe84eb9dd/artifacts
end_time: 1763361538342
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 46d63f60276145fd9ac726abe84eb9dd
run_name: debonair-turtle-704
source_name: ''
source_type: 4
source_version: ''
start_time: 1763361472439
status: 3
tags: []
user_id: DELL
