artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/848600ae65bf41edaa718c5aa7574acf/artifacts
end_time: 1763355648620
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 848600ae65bf41edaa718c5aa7574acf
run_name: overjoyed-shrew-643
source_name: ''
source_type: 4
source_version: ''
start_time: 1763355638970
status: 4
tags: []
user_id: DELL
