artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/1afcfb9ab7694e4ea7800285bd20c541/artifacts
end_time: 1763357175947
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 1afcfb9ab7694e4ea7800285bd20c541
run_name: brawny-carp-390
source_name: ''
source_type: 4
source_version: ''
start_time: 1763357112055
status: 4
tags: []
user_id: DELL
