artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/afeb5d22ac4047c5baea2f7461d9f420/artifacts
end_time: 1763350130763
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: afeb5d22ac4047c5baea2f7461d9f420
run_name: loud-rook-68
source_name: ''
source_type: 4
source_version: ''
start_time: 1763350118790
status: 3
tags: []
user_id: DELL
