artifact_location: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767
creation_time: 1763305834018
experiment_id: '456839572495102767'
last_update_time: 1763305834018
lifecycle_stage: active
name: medical_rag_experiment
