artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/dd0d439704d148e58fd03d49aba1cd18/artifacts
end_time: 1763305846264
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: dd0d439704d148e58fd03d49aba1cd18
run_name: handsome-dog-999
source_name: ''
source_type: 4
source_version: ''
start_time: 1763305835483
status: 4
tags: []
user_id: DELL
