artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/8f18b7ae5bc147efa5b66ae7fbb363b3/artifacts
end_time: 1763359790136
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 8f18b7ae5bc147efa5b66ae7fbb363b3
run_name: indecisive-dove-934
source_name: ''
source_type: 4
source_version: ''
start_time: 1763359725752
status: 3
tags: []
user_id: DELL
