artifact_uri: file:///D:/End_to_End/Medical_chatbot/Medical-Chatbot/mlflow_artifacts/456839572495102767/3ccc1aac037f4fa994fda39d9c2b1c4a/artifacts
end_time: 1763306071897
entry_point_name: ''
experiment_id: '456839572495102767'
lifecycle_stage: active
run_id: 3ccc1aac037f4fa994fda39d9c2b1c4a
run_name: incongruous-chimp-57
source_name: ''
source_type: 4
source_version: ''
start_time: 1763306060760
status: 3
tags: []
user_id: DELL
